/**
 * Short-lived store for puzzles generated by POST /api/puzzles/live. A multiplayer host
 * redeems the token once (create_room), so every participant gets the same grid.
 */
import crypto from 'crypto';
import { logger } from '../logger.js';

const LIVE_PUZZLE_TTL_MS = 5 * 60 * 1000;
const MAX_LIVE_PUZZLES = 100;

export function createLivePuzzleStore({
  ttlMs = LIVE_PUZZLE_TTL_MS,
  maxEntries = MAX_LIVE_PUZZLES,
  createToken = crypto.randomUUID,
} = {}) {
  const puzzles = new Map();
  const capacity = Math.max(1, maxEntries);

  function remove(token) {
    const record = puzzles.get(token);
    if (!record) return null;
    clearTimeout(record.expiryTimer);
    puzzles.delete(token);
    return record;
  }

  function expire(token) {
    const record = puzzles.get(token);
    if (!record) return;
    const remainingMs = record.expiresAt - Date.now();
    if (remainingMs > 0) {
      record.expiryTimer = setTimeout(() => expire(token), remainingMs);
      record.expiryTimer.unref?.();
      return;
    }
    puzzles.delete(token);
  }

  function removeExpired() {
    for (const [token, record] of puzzles) {
      if (record.expiresAt <= Date.now()) remove(token);
    }
  }

  return {
    add(puzzle) {
      removeExpired();
      while (puzzles.size >= capacity) {
        const evicted = puzzles.keys().next().value;
        remove(evicted);
        logger.store('evicted', evicted, '(capacity reached)');
      }

      const token = createToken();
      const record = {
        puzzle,
        expiresAt: Date.now() + ttlMs,
        expiryTimer: null,
      };
      puzzles.set(token, record);
      record.expiryTimer = setTimeout(() => expire(token), ttlMs);
      record.expiryTimer.unref?.();
      logger.store('created', token, `(active: ${puzzles.size})`);
      return token;
    },
    consume(token) {
      const record = puzzles.get(token);
      if (!record || record.expiresAt <= Date.now()) {
        remove(token);
        logger.store('expired_on_consume', token);
        return null;
      }
      logger.store('consumed', token);
      return remove(token);
    },
    clear() {
      for (const token of puzzles.keys()) remove(token);
    },
    get size() {
      removeExpired();
      return puzzles.size;
    },
  };
}
